DROP TABLE IF EXISTS data;

CREATE TABLE data (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    e_id INTEGER NOT NULL,
    e_category VARCHAR(255) NOT NULL,
    watch_start TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    watch_end TIMESTAMP
);